use ../lib/logger.nu log
use ../lib/error.nu mkerr


# Run a multi-model swarm analysis on a prompt piped via stdin.
#
# INPUT
#   Pipe your analysis prompt as a string through stdin:
#     "Analyse the migration gaps in this codebase" | swarm
#
#   Alternatively, write the prompt to ./harness/00_task.md and run
#   swarm with no stdin — it will read the file automatically.
#
# FLAGS
#   --max-rounds  Maximum number of swarm → critic refinement rounds (default: 3).
#                 Each intermediate round the critic produces a Feedback Report
#                 fed back to the swarm. The final round produces the consensus.
#
# CONFIGURATION  (.swarm-config.json, optional)
#   Place a .swarm-config.json file in the working directory to override
#   the default models. Both fields are optional.
#
#   Example with default values:
#     {
#       "critic_model": "gpt-5.4",
#       "swarm_models": [
#         "claude-sonnet-5", "gpt-5.3-codex", "gemini-3.1-pro-preview"
#       ]
#     }
#
# HARNESS DIRECTORY (./.harness/)
#   The command reads from and writes to a ./.harness/ directory in the
#   working directory. It is created automatically if it does not exist.
#
#   .harness/
#   ├── 00_task.md                       # (optional) stdin prompt fallback
#   ├── 01_context.md                    # (optional) swarm background context
#   ├── 02_analysis_<model>_r<N>.md      # (output)   swarm analysis per model
#   ├── 02_feedback_r<N>.md              # (output)   critic feedback report
#   └── 03_consensus_<model>.md          # (output)   final critic consensus
#
# AVAILABLE MODELS
#   claude-sonnet-5         General-purpose coding (default)
#   gpt-5.4                 Complex reasoning tasks
#   claude-haiku-4.5        Fast, lightweight operations
#   gpt-5.3-codex           Code-focused tasks
#   gemini-3.1-pro-preview  Google Gemini reasoning
#   gemini-3.5-flash        Fast Google Gemini responses
#   mai-code-1-flash        Fast, adaptive coding tasks
export def main [
    --max-rounds: int = 3  # Maximum swarm → critic refinement rounds
]: [nothing -> nothing, string -> nothing] {
    

    # --- constants -----------------------------------------------------------

    const default_config = {
        critic_model: "gpt-5.4"
        swarm_models: ["claude-sonnet-5", "gpt-5.3-codex", "gemini-3.1-pro-preview"]
    }
    const harness_dir = "./.harness"
    const config_file = ".swarm-config.json"
    const task_file = "00_task.md"
    const context_file = "01_context.md"
    const analysis_prefix = "02_analysis_"
    const feedback_prefix = "02_feedback_"
    const consensus_prefix = "03_consensus_"

    # --- system prompts ------------------------------------------------------

    let swarm_system_prompt = "
You are an independent analytical agent. Your task is to evaluate the provided
context and execute the user's prompt objectively.

Execution Rules:
1. Strict Grounding: Base your analysis and outputs entirely on the provided
CONTEXT. Do not introduce external facts, assume missing data, or generate
hypothetical scenarios unless explicitly requested.
2. Exhaustive Extraction: Address all constraints and requirements outlined in
the user's PROMPT.
3. Logical Transparency: Provide clear, step-by-step reasoning for your
conclusions. 
4. Ambiguity Handling: If the context is insufficient to answer a part of the
prompt, state the specific missing information directly rather than guessing.

Respond directly to the prompt without introductory conversational filler.
"
    let critic_feedback_prompt = "
You are the Critic Agent running an intermediate review.

Your task is NOT to produce a final answer. Cross-reference the agent analyses
below and identify discrepancies, gaps, and missed areas between them.

Execution Rules:
1. Identify Conflicts: Flag any point where agents contradict each other.
2. Identify Gaps: Flag anything that only one agent mentioned — these are
unverified and need a second opinion.
3. Targeted Feedback: For each gap or conflict, address the specific agent(s)
responsible and state exactly what they missed or got wrong, citing evidence.
4. No Final Plan: Do not synthesise a conclusion. Output only the Feedback
Report so the agents can revise their analyses in the next round.
"
    let critic_system_prompt = "
You are the Consensus and Synthesis Agent. You are receiving independent
outputs from multiple AI agents that evaluated the identical CONTEXT and PROMPT. 

Your mandate is to synthesize a high-confidence final response based on
multi-agent consensus.

Execution Rules:
1. Cross-Reference: Compare all agent outputs to identify intersecting
agreements and conflicting claims.
2. Intersection Filtering (Strict): Discard any claim, fact, or proposed
solution that was generated by only a single agent. Retain only points where
multiple agents share consensus.
3. Conflict Resolution: If agents fundamentally disagree on a core premise,
objectively state the differing perspectives, but exclude both from the final
factual synthesis.
4. Final Synthesis: Combine the verified, multi-agent consensus points into a
single, cohesive response that directly answers the original PROMPT.

Do not mention the individual agents or the consensus process in your final
output. Present the synthesized result directly.
"

    # --- resolve prompt ------------------------------------------------------

    let task_path = $harness_dir | path join $task_file
    let stdin_input = $in
    let user_prompt = if ($stdin_input | is-empty) {
        if ($task_path | path exists) {
            log warn $"No stdin prompt — reading from ($task_path)"
            open --raw $task_path | into string
        } else {
            mkerr $"No prompt provided: pipe a string via stdin or create ($task_path)"
        }
    } else {
        $stdin_input
    }

    # --- load config ---------------------------------------------------------

    let config = if ($config_file | path exists) {
        $default_config | merge (open $config_file)
    } else {
        $default_config
    }
    let swarm_models = $config.swarm_models
    let critic_model = $config.critic_model

    # --- ensure harness directory exists -------------------------------------

    if not ($harness_dir | path exists) {
        mkdir $harness_dir
    }

    # --- load context (optional) ---------------------------------------------

    let context_path = $harness_dir | path join $context_file
    let context = if ($context_path | path exists) {
        open --raw $context_path | into string
    } else {
        log warn $"No context file found at ($context_path)"
        ""
    }
    let context_section = if ($context | is-empty) {
        ""
    } else {
        $"\n\n--- ADDITIONAL CONTEXT ---\n($context)"
    }

    # --- iterative refinement loop -------------------------------------------

    mut feedback = ""
    for round in 1..$max_rounds {
        log info $"Round ($round) of ($max_rounds): running swarm agents \(($swarm_models | str join ', ')\)..."
        let prev_round = $round - 1
        let feedback_section = if ($feedback | is-empty) {
            ""
        } else {
            $"\n\n--- CRITIC FEEDBACK \(Round ($prev_round)\) ---\n($feedback)"
        }
        let full_swarm_prompt = $"--- SYSTEM PROMPT ---\n($swarm_system_prompt)($context_section)($feedback_section)\n\n--- USER PROMPT ---\n($user_prompt)"

        # run swarm agents in parallel
        $swarm_models | par-each {|model|
            let output_path = $harness_dir | path join $"($analysis_prefix)($model)_r($round).md"
            copilot --silent --model $model -p $full_swarm_prompt --allow-all-tools | save --force $output_path
        }

        # aggregate analyses for the critic
        let aggregated_analyses = ($swarm_models | each {|model|
            let analysis_path = $harness_dir | path join $"($analysis_prefix)($model)_r($round).md"
            let file_content = open --raw $analysis_path | into string
            $"--- Analysis from ($model) ---\n($file_content)\n"
        } | str join "\n")
        if $round < $max_rounds {

            # intermediate round: critic produces a feedback report
            log info $"Round ($round): running critic \(($critic_model)\) for feedback..."
            let full_critic_prompt = $"--- SYSTEM PROMPT ---\n($critic_feedback_prompt)\n\n--- ADDITIONAL CONTEXT ---\n($aggregated_analyses)"
            let feedback_path = $harness_dir | path join $"($feedback_prefix)r($round).md"
            let new_feedback = (
                copilot --silent --model $critic_model -p $full_critic_prompt --allow-all-tools
            )
            $new_feedback | save --force $feedback_path
            $feedback = $new_feedback
        } else {

            # final round: critic produces the consensus plan
            log info $"Round ($round): running critic \(($critic_model)\) for final synthesis..."
            let full_critic_prompt = $"--- SYSTEM PROMPT ---\n($critic_system_prompt)\n\n--- ADDITIONAL CONTEXT ---\n($aggregated_analyses)"
            let consensus_path = $harness_dir | path join $"($consensus_prefix)($critic_model).md"
            copilot --silent --model $critic_model -p $full_critic_prompt --allow-all-tools | save --force $consensus_path
        }
    }
}
